//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK
{
    using FormanceSDK.Models.Components;
    using FormanceSDK.Models.Errors;
    using FormanceSDK.Utils;
    using System;

    public interface IAuth
    {
        public IV1 V1 { get; }
    }

    public class Auth: IAuth
    {
        /// <summary>
        /// SDK Configuration.
        /// <see cref="SDKConfig"/>
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }

        /// <summary>
        /// V1 SubSDK.
        /// <see cref="IV1"/>
        /// </summary>
        public IV1 V1 { get; private set; }

        public Auth(SDKConfig config)
        {
            SDKConfiguration = config;
            V1 = new V1(SDKConfiguration);
        }
    }
}