//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK
{
    using FormanceSDK.Models.Components;
    using FormanceSDK.Models.Errors;
    using FormanceSDK.Utils;
    using System;

    public interface ILedger
    {
        public IFormanceV1 V1 { get; }

        public IV2 V2 { get; }
    }

    public class Ledger: ILedger
    {
        /// <summary>
        /// SDK Configuration.
        /// <see cref="SDKConfig"/>
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }

        /// <summary>
        /// V1 SubSDK.
        /// <see cref="IFormanceV1"/>
        /// </summary>
        public IFormanceV1 V1 { get; private set; }

        /// <summary>
        /// V2 SubSDK.
        /// <see cref="IV2"/>
        /// </summary>
        public IV2 V2 { get; private set; }

        public Ledger(SDKConfig config)
        {
            SDKConfiguration = config;
            V1 = new FormanceV1(SDKConfiguration);
            V2 = new V2(SDKConfiguration);
        }
    }
}