//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK
{
    using FormanceSDK.Models.Components;
    using FormanceSDK.Models.Errors;
    using FormanceSDK.Utils;
    using System;

    public interface IOrchestration
    {
        public IFormanceOrchestrationV1 V1 { get; }

        public IFormanceV2 V2 { get; }
    }

    public class Orchestration: IOrchestration
    {
        /// <summary>
        /// SDK Configuration.
        /// <see cref="SDKConfig"/>
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }

        /// <summary>
        /// V1 SubSDK.
        /// <see cref="IFormanceOrchestrationV1"/>
        /// </summary>
        public IFormanceOrchestrationV1 V1 { get; private set; }

        /// <summary>
        /// V2 SubSDK.
        /// <see cref="IFormanceV2"/>
        /// </summary>
        public IFormanceV2 V2 { get; private set; }

        public Orchestration(SDKConfig config)
        {
            SDKConfiguration = config;
            V1 = new FormanceOrchestrationV1(SDKConfiguration);
            V2 = new FormanceV2(SDKConfiguration);
        }
    }
}