//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Errors
{
    using FormanceSDK.Models.Components;
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Net.Http;

    public class PaymentsErrorResponsePayload
    {
        [JsonProperty("errorCode")]
        public PaymentsErrorsEnum ErrorCode { get; set; } = default!;

        [JsonProperty("errorMessage")]
        public string ErrorMessage { get; set; } = default!;
    }

    /// <summary>
    /// Error
    /// </summary>
    public class PaymentsErrorResponse : FormanceError
    {
        /// <summary>
        ///  The original data that was passed to this exception.
        /// </summary>
        public PaymentsErrorResponsePayload Payload { get; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use PaymentsErrorResponse.Payload.ErrorCode instead.")]
        public PaymentsErrorsEnum ErrorCode { get; set; } = default!;

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use PaymentsErrorResponse.Payload.ErrorMessage instead.")]
        public string ErrorMessage { get; set; } = default!;

        public PaymentsErrorResponse(
            PaymentsErrorResponsePayload payload,
            HttpRequestMessage request,
            HttpResponseMessage response,
            string body
        ): base("API error occurred", request, response, body)
        {
           Payload = payload;

           #pragma warning disable CS0618
           ErrorCode = payload.ErrorCode;
           ErrorMessage = payload.ErrorMessage;
           #pragma warning restore CS0618
        }
    }

}