//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace formance.Models.Requests
{
    using formance.Models.Components;
    using formance.Utils;
    
    public class ListConnectorTasksV1Request
    {

        /// <summary>
        /// The name of the connector.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=connector")]
        public Connector Connector { get; set; } = default!;

        /// <summary>
        /// The connector ID.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=connectorId")]
        public string ConnectorId { get; set; } = default!;

        /// <summary>
        /// The maximum number of results to return per page.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=pageSize")]
        public long? PageSize { get; set; } = 15;

        /// <summary>
        /// Parameter used in pagination requests. Maximum page size is set to 15.<br/>
        /// 
        /// <remarks>
        /// Set to the value of next for the next page of results.<br/>
        /// Set to the value of previous for the previous page of results.<br/>
        /// No other parameters can be set when this parameter is set.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=cursor")]
        public string? Cursor { get; set; }
    }
}