//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Webhooks
{
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using System;

    public enum Outcome
    {
        [JsonProperty("succeeded")]
        Succeeded,
        [JsonProperty("retryable_failure")]
        RetryableFailure,
        [JsonProperty("permanent_failure")]
        PermanentFailure,
    }

    public static class OutcomeExtension
    {
        public static string Value(this Outcome value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static Outcome ToEnum(this string value)
        {
            foreach(var field in typeof(Outcome).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is Outcome)
                    {
                        return (Outcome)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum Outcome");
        }
    }
}