//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Webhooks
{
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using System;

    public class ReplayDeliveriesResult
    {
        [JsonProperty("replayed")]
        public long Replayed { get; set; } = default!;

        [JsonProperty("expedited")]
        public long Expedited { get; set; } = default!;

        [JsonProperty("skipped")]
        public long Skipped { get; set; } = default!;

        [JsonProperty("hasMore")]
        public bool HasMore { get; set; } = default!;

        [JsonProperty("nextCursor")]
        public string? NextCursor { get; set; }

        [JsonProperty("createdAtTo")]
        public DateTime CreatedAtTo { get; set; } = default!;
    }
}