//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Requests
{
    using FormanceSDK.Utils;
    
    public class GetManyConfigsRequest
    {

        /// <summary>
        /// Optional filter by Config ID
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=id")]
        public string? Id { get; set; }

        /// <summary>
        /// Optional filter by endpoint URL
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=endpoint")]
        public string? Endpoint { get; set; }
    }
}