//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Requests
{
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// The field to sort by.
    /// </summary>
    public enum Sort
    {
        [JsonProperty("created_at")]
        CreatedAt,
    }

    public static class SortExtension
    {
        public static string Value(this Sort value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static Sort ToEnum(this string value)
        {
            foreach(var field in typeof(Sort).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is Sort)
                    {
                        return (Sort)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum Sort");
        }
    }
}