//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Requests
{
    using FormanceSDK.Models.Components;
    using FormanceSDK.Utils;
    
    public class UninstallConnectorV1Request
    {

        /// <summary>
        /// The name of the connector.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=connector")]
        public Connector Connector { get; set; } = default!;

        /// <summary>
        /// The connector ID.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=connectorId")]
        public string ConnectorId { get; set; } = default!;
    }
}