//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Requests
{
    using FormanceSDK.Utils;
    using System.Collections.Generic;
    
    public class V2RunWorkflowRequest
    {

        /// <summary>
        /// The flow id
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=workflowID")]
        public string WorkflowID { get; set; } = default!;

        /// <summary>
        /// Wait end of the workflow before return
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=wait")]
        public bool? Wait { get; set; }

        [SpeakeasyMetadata("request:mediaType=application/json")]
        public Dictionary<string, string>? RequestBody { get; set; }
    }
}