//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Ledger
{
    using FormanceSDK.Models.Ledger;
    using FormanceSDK.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Created exporter.
    /// </summary>
    public class V2CreateExporterResponse
    {
        [JsonProperty("data")]
        public V2ExporterConfiguration V2ExporterConfiguration { get; set; } = default!;
    }
}