//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Ledger
{
    using FormanceSDK.Models.Components;
    using FormanceSDK.Models.Ledger;
    using FormanceSDK.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Payload for DELETE_METADATA log entries. Contains the target entity and the metadata key that was deleted.
    /// </summary>
    public class V2LogDataDeleteMetadata
    {
        /// <summary>
        /// Type of the target entity.
        /// </summary>
        [JsonProperty("targetType")]
        public V2LogDataDeleteMetadataTargetType TargetType { get; set; } = default!;

        [JsonProperty("targetId", NullValueHandling = NullValueHandling.Include)]
        public V2LogDataDeleteMetadataTargetId TargetId { get; set; } = default!;

        /// <summary>
        /// The metadata key that was deleted.
        /// </summary>
        [JsonProperty("key")]
        public string Key { get; set; } = default!;
    }
}