//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Ledger
{
    using FormanceSDK.Models.Ledger;
    using FormanceSDK.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Payload for INSERTED_SCHEMA log entries. Contains the schema that was inserted into the ledger.
    /// </summary>
    public class V2LogDataInsertedSchema
    {
        /// <summary>
        /// Complete schema structure with metadata.
        /// </summary>
        [JsonProperty("schema")]
        public V2SchemaData1 V2SchemaData { get; set; } = default!;
    }
}