//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Ledger
{
    using FormanceSDK.Models.Components;
    using FormanceSDK.Models.Ledger;
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class V2QueryTemplate
    {
        [JsonProperty("description")]
        public string? Description { get; set; }

        [JsonProperty("resource")]
        public V2QueryResource? V2QueryResource { get; set; }

        [JsonProperty("params", NullValueHandling = NullValueHandling.Include)]
        public V2QueryParams? V2QueryParams { get; set; }

        [JsonProperty("vars")]
        public Dictionary<string, V2QueryTemplateVar>? Vars { get; set; }

        [JsonProperty("body")]
        public Dictionary<string, object>? Body { get; set; }
    }
}