//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace formance.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using formance.Models.Components;
    using formance.Utils;
    
    public class Client
    {

        [JsonProperty("public")]
        public bool? Public { get; set; }

        [JsonProperty("redirectUris")]
        public List<string>? RedirectUris { get; set; }

        [JsonProperty("description")]
        public string? Description { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [JsonProperty("trusted")]
        public bool? Trusted { get; set; }

        [JsonProperty("postLogoutRedirectUris")]
        public List<string>? PostLogoutRedirectUris { get; set; }

        [JsonProperty("metadata")]
        public Dictionary<string, object>? Metadata { get; set; }

        [JsonProperty("scopes")]
        public List<string>? Scopes { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        [JsonProperty("secrets")]
        public List<ClientSecret>? Secrets { get; set; }
    }
}