//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace formance.Models.Components
{
    using Newtonsoft.Json;
    using formance.Models.Components;
    using formance.Utils;
    
    public class ConfigInfo
    {

        [JsonProperty("config")]
        public Config Config { get; set; } = default!;

        [JsonProperty("server")]
        public string Server { get; set; } = default!;

        [JsonProperty("version")]
        public string Version { get; set; } = default!;
    }
}