//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace formance.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using formance.Models.Components;
    using formance.Utils;
    
    public class Log
    {

        [JsonProperty("id")]
        public long Id { get; set; } = default!;

        [JsonProperty("type")]
        public Models.Components.Type Type { get; set; } = default!;

        [JsonProperty("data")]
        public Dictionary<string, object> Data { get; set; } = default!;

        [JsonProperty("hash")]
        public string Hash { get; set; } = default!;

        [JsonProperty("date")]
        public DateTime Date { get; set; } = default!;
    }
}