//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace formance.Models.Components
{
    using Newtonsoft.Json;
    using formance.Utils;
    
    public class MoneycorpConfig
    {

        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [JsonProperty("clientID")]
        public string ClientID { get; set; } = default!;

        [JsonProperty("apiKey")]
        public string ApiKey { get; set; } = default!;

        [JsonProperty("endpoint")]
        public string Endpoint { get; set; } = default!;

        /// <summary>
        /// The frequency at which the connector will try to fetch new BalanceTransaction objects from MoneyCorp API.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("pollingPeriod")]
        public string? PollingPeriod { get; set; } = "120s";
    }
}