//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace formance.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System.Numerics;
    using System;
    using formance.Models.Components;
    using formance.Utils;
    
    public class OrchestrationPayment
    {

        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        [JsonProperty("reference")]
        public string Reference { get; set; } = default!;

        [JsonProperty("sourceAccountID")]
        public string SourceAccountID { get; set; } = default!;

        [JsonProperty("destinationAccountID")]
        public string DestinationAccountID { get; set; } = default!;

        [JsonProperty("connectorID")]
        public string ConnectorID { get; set; } = default!;

        [JsonProperty("provider")]
        public OrchestrationConnector? Provider { get; set; }

        [JsonProperty("type")]
        public OrchestrationPaymentType Type { get; set; } = default!;

        [JsonProperty("status")]
        public OrchestrationPaymentStatus Status { get; set; } = default!;

        [JsonProperty("initialAmount")]
        public BigInteger InitialAmount { get; set; } = default!;

        [JsonProperty("scheme")]
        public Scheme Scheme { get; set; } = default!;

        [JsonProperty("asset")]
        public string Asset { get; set; } = default!;

        [JsonProperty("createdAt")]
        public DateTime CreatedAt { get; set; } = default!;

        [JsonProperty("raw", NullValueHandling = NullValueHandling.Include)]
        public OrchestrationPaymentRaw? Raw { get; set; }

        [JsonProperty("adjustments")]
        public List<OrchestrationPaymentAdjustment> Adjustments { get; set; } = default!;

        [JsonProperty("metadata", NullValueHandling = NullValueHandling.Include)]
        public OrchestrationPaymentMetadata? Metadata { get; set; }
    }
}