//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace formance.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using formance.Utils;
    
    public enum PaymentsErrorsEnum
    {
        [JsonProperty("INTERNAL")]
        Internal,
        [JsonProperty("VALIDATION")]
        Validation,
        [JsonProperty("NOT_FOUND")]
        NotFound,
    }

    public static class PaymentsErrorsEnumExtension
    {
        public static string Value(this PaymentsErrorsEnum value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static PaymentsErrorsEnum ToEnum(this string value)
        {
            foreach(var field in typeof(PaymentsErrorsEnum).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is PaymentsErrorsEnum)
                    {
                        return (PaymentsErrorsEnum)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum PaymentsErrorsEnum");
        }
    }

}