//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace formance.Models.Components
{
    using Newtonsoft.Json;
    using formance.Utils;
    
    public class TaskMangoPayDescriptor
    {

        [JsonProperty("name")]
        public string? Name { get; set; }

        [JsonProperty("key")]
        public string? Key { get; set; }

        [JsonProperty("userID")]
        public string? UserID { get; set; }
    }
}