//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace formance.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using formance.Utils;
    
    public enum V2MigrationInfoState
    {
        [JsonProperty("TO DO")]
        ToDo,
        [JsonProperty("DONE")]
        Done,
    }

    public static class V2MigrationInfoStateExtension
    {
        public static string Value(this V2MigrationInfoState value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static V2MigrationInfoState ToEnum(this string value)
        {
            foreach(var field in typeof(V2MigrationInfoState).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is V2MigrationInfoState)
                    {
                        return (V2MigrationInfoState)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum V2MigrationInfoState");
        }
    }

}