//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace formance.Models.Components
{
    using Newtonsoft.Json;
    using System.Numerics;
    using formance.Utils;
    
    public class V2Monetary
    {

        /// <summary>
        /// The asset of the monetary value.
        /// </summary>
        [JsonProperty("asset")]
        public string Asset { get; set; } = default!;

        /// <summary>
        /// The amount of the monetary value.
        /// </summary>
        [JsonProperty("amount")]
        public BigInteger Amount { get; set; } = default!;
    }
}