//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace formance.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using formance.Utils;
    
    public class V2PostTransactionScript
    {

        [JsonProperty("plain")]
        public string Plain { get; set; } = default!;

        [JsonProperty("vars")]
        public Dictionary<string, object>? Vars { get; set; }
    }
}