//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace formance.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using formance.Models.Components;
    using formance.Utils;
    
    public class V2WorkflowInstance
    {

        [JsonProperty("workflowID")]
        public string WorkflowID { get; set; } = default!;

        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        [JsonProperty("createdAt")]
        public DateTime CreatedAt { get; set; } = default!;

        [JsonProperty("updatedAt")]
        public DateTime UpdatedAt { get; set; } = default!;

        [JsonProperty("status")]
        public List<V2StageStatus>? Status { get; set; }

        [JsonProperty("terminated")]
        public bool Terminated { get; set; } = default!;

        [JsonProperty("terminatedAt")]
        public DateTime? TerminatedAt { get; set; }

        [JsonProperty("error")]
        public string? Error { get; set; }
    }
}