//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace formance.Models.Components
{
    using Newtonsoft.Json;
    using System.Numerics;
    using formance.Utils;
    
    public class WalletsVolume
    {

        [JsonProperty("input")]
        public BigInteger Input { get; set; } = default!;

        [JsonProperty("output")]
        public BigInteger Output { get; set; } = default!;

        [JsonProperty("balance")]
        public BigInteger Balance { get; set; } = default!;
    }
}