workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://github.com/formancehq/stack/releases/download/v2.1.0-beta.3/generate.json
        registry:
            location: registry.speakeasyapi.dev/formance/formance/my-source
targets:
    formance:
        target: csharp
        source: my-source
        publish:
            nuget:
                apiKey: $nuget_api_key
