//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Reconciliation
{
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// Mark an alert resolved. When `transactionRefs` is non-empty the<br/>
    /// resolution kind is recorded as `fixed_by_booking`.
    /// </summary>
    public class ResolveAlertRequest
    {
        [JsonProperty("by")]
        public string By { get; set; } = default!;

        [JsonProperty("note")]
        public string? Note { get; set; }

        [JsonProperty("transactionRefs")]
        public List<string>? TransactionRefs { get; set; }
    }
}