//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Reconciliation
{
    using FormanceSDK.Models.Reconciliation;
    using FormanceSDK.Utils;
    using Newtonsoft.Json;

    public class Schedule
    {
        [JsonProperty("kind")]
        public Kind Kind { get; set; } = default!;

        [JsonProperty("expr")]
        public string? Expr { get; set; }

        [JsonProperty("tz")]
        public string? Tz { get; set; }

        /// <summary>
        /// Go duration string.
        /// </summary>
        [JsonProperty("safetyMargin")]
        public string? SafetyMargin { get; set; }
    }
}