//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Reconciliation
{
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using System;

    public enum TemplateKind
    {
        [JsonProperty("ledger_vs_pool_drift")]
        LedgerVsPoolDrift,
        [JsonProperty("ledger_invariant")]
        LedgerInvariant,
        [JsonProperty("account_threshold")]
        AccountThreshold,
        [JsonProperty("source_parity")]
        SourceParity,
    }

    public static class TemplateKindExtension
    {
        public static string Value(this TemplateKind value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static TemplateKind ToEnum(this string value)
        {
            foreach(var field in typeof(TemplateKind).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is TemplateKind)
                    {
                        return (TemplateKind)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum TemplateKind");
        }
    }
}