//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Components
{
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    
    public class BalanceWithAssets
    {

        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [JsonProperty("expiresAt")]
        public DateTime? ExpiresAt { get; set; } = null;

        [JsonProperty("priority")]
        public BigInteger? Priority { get; set; }

        [JsonProperty("assets")]
        public Dictionary<string, BigInteger> Assets { get; set; } = default!;
    }
}