//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Components
{
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    
    public class Descriptor
    {

        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [JsonProperty("main")]
        public bool? Main { get; set; }

        [JsonProperty("account")]
        public string Account { get; set; } = default!;
    }
}