//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Components
{
    using FormanceSDK.Models.Components;
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    
    public class TransferInitiation
    {

        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        [JsonProperty("reference")]
        public string Reference { get; set; } = default!;

        [JsonProperty("createdAt")]
        public DateTime CreatedAt { get; set; } = default!;

        [JsonProperty("scheduledAt")]
        public DateTime ScheduledAt { get; set; } = default!;

        [JsonProperty("description")]
        public string Description { get; set; } = default!;

        [JsonProperty("sourceAccountID")]
        public string SourceAccountID { get; set; } = default!;

        [JsonProperty("destinationAccountID")]
        public string DestinationAccountID { get; set; } = default!;

        [JsonProperty("connectorID")]
        public string ConnectorID { get; set; } = default!;

        [JsonProperty("provider", NullValueHandling = NullValueHandling.Include)]
        public string? Provider { get; set; }

        [JsonProperty("type")]
        public TransferInitiationType Type { get; set; } = default!;

        [JsonProperty("amount")]
        public BigInteger Amount { get; set; } = default!;

        [JsonProperty("initialAmount")]
        public BigInteger InitialAmount { get; set; } = default!;

        [JsonProperty("asset")]
        public string Asset { get; set; } = default!;

        [JsonProperty("status")]
        public TransferInitiationStatus Status { get; set; } = default!;

        [JsonProperty("error")]
        public string? Error { get; set; } = null;

        [JsonProperty("metadata")]
        public Dictionary<string, string>? Metadata { get; set; } = null;

        [JsonProperty("relatedPayments")]
        public List<TransferInitiationPayments>? RelatedPayments { get; set; } = null;

        [JsonProperty("relatedAdjustments")]
        public List<TransferInitiationAdjusments>? RelatedAdjustments { get; set; }
    }
}