//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Components
{
    using FormanceSDK.Models.Components;
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    
    public class V2Log
    {

        [JsonProperty("id")]
        public BigInteger Id { get; set; } = default!;

        [JsonProperty("type")]
        public V2LogType Type { get; set; } = default!;

        [JsonProperty("data")]
        public Dictionary<string, object> Data { get; set; } = default!;

        [JsonProperty("hash")]
        public string Hash { get; set; } = default!;

        [JsonProperty("date")]
        public DateTime Date { get; set; } = default!;
    }
}