//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Components
{
    using FormanceSDK.Models.Components;
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    
    public class V2StageSendSource
    {

        [JsonProperty("wallet")]
        public V2StageSendSourceWallet? Wallet { get; set; }

        [JsonProperty("account")]
        public V2StageSendSourceAccount? Account { get; set; }

        [JsonProperty("payment")]
        public V2StageSendSourcePayment? Payment { get; set; }
    }
}