//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Components
{
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    
    public class V3DummypayConfig
    {

        [JsonProperty("directory")]
        public string Directory { get; set; } = default!;

        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [JsonProperty("pageSize")]
        public long? PageSize { get; set; } = 25;

        [JsonProperty("pollingPeriod")]
        public string? PollingPeriod { get; set; } = "2m";
    }
}