//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Components
{
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    public enum V3PaymentInitiationTypeEnum
    {
        [JsonProperty("UNKNOWN")]
        Unknown,
        [JsonProperty("TRANSFER")]
        Transfer,
        [JsonProperty("PAYOUT")]
        Payout,
    }

    public static class V3PaymentInitiationTypeEnumExtension
    {
        public static string Value(this V3PaymentInitiationTypeEnum value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static V3PaymentInitiationTypeEnum ToEnum(this string value)
        {
            foreach(var field in typeof(V3PaymentInitiationTypeEnum).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is V3PaymentInitiationTypeEnum)
                    {
                        return (V3PaymentInitiationTypeEnum)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum V3PaymentInitiationTypeEnum");
        }
    }

}