//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Orchestration
{
    using FormanceSDK.Models.Orchestration;
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Numerics;

    public class PaymentAdjustment
    {
        [JsonProperty("status")]
        public Models.Orchestration.PaymentStatus PaymentStatus { get; set; } = default!;

        [JsonProperty("amount")]
        public BigInteger Amount { get; set; } = default!;

        [JsonProperty("date")]
        public DateTime Date { get; set; } = default!;

        [JsonProperty("raw")]
        public Models.Orchestration.PaymentAdjustmentRaw Raw { get; set; } = default!;

        [JsonProperty("absolute")]
        public bool Absolute { get; set; } = default!;
    }
}