//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Orchestration
{
    using FormanceSDK.Models.Orchestration;
    using FormanceSDK.Utils;
    using Newtonsoft.Json;

    public class StageSendDestinationPayment
    {
        /// <summary>
        /// Payment service provider name (e.g., stripe, wise, mangopay).<br/>
        /// Validated by the Payments service based on installed connectors.
        /// </summary>
        [JsonProperty("psp")]
        public string Psp { get; set; } = default!;

        /// <summary>
        /// Type of transfer initiation:<br/>
        /// - TRANSFER: Internal to internal account transfer<br/>
        /// - PAYOUT: Internal to external account payout.
        /// </summary>
        [JsonProperty("type")]
        public Models.Orchestration.Type? Type { get; set; } = FormanceSDK.Models.Orchestration.Type.Transfer;

        /// <summary>
        /// Formance Payments account ID for the source (internal PSP account).<br/>
        /// If not specified, the Payments service may use a default account for the connector.
        /// </summary>
        [JsonProperty("sourceAccount")]
        public string? SourceAccount { get; set; }
    }
}