//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Orchestration
{
    using FormanceSDK.Models.Orchestration;
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class V2SubjectType
    {
        private V2SubjectType(string value) { Value = value; }

        public string Value { get; private set; }

        public static V2SubjectType V2LedgerAccountSubject { get { return new V2SubjectType("V2LedgerAccountSubject"); } }

        public static V2SubjectType V2WalletSubject { get { return new V2SubjectType("V2WalletSubject"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(V2SubjectType v) { return v.Value; }
        public static V2SubjectType FromString(string v) {
            switch(v) {
                case "V2LedgerAccountSubject": return V2LedgerAccountSubject;
                case "V2WalletSubject": return V2WalletSubject;
                default: throw new ArgumentException("Invalid value for V2SubjectType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((V2SubjectType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(V2Subject.V2SubjectConverter))]
    public class V2Subject
    {
        public V2Subject(V2SubjectType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public V2LedgerAccountSubject? V2LedgerAccountSubject { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public V2WalletSubject? V2WalletSubject { get; set; }

        public V2SubjectType Type { get; set; }
        public static V2Subject CreateV2LedgerAccountSubject(V2LedgerAccountSubject v2LedgerAccountSubject)
        {
            V2SubjectType typ = V2SubjectType.V2LedgerAccountSubject;

            V2Subject res = new V2Subject(typ);
            res.V2LedgerAccountSubject = v2LedgerAccountSubject;
            return res;
        }
        public static V2Subject CreateV2WalletSubject(V2WalletSubject v2WalletSubject)
        {
            V2SubjectType typ = V2SubjectType.V2WalletSubject;

            V2Subject res = new V2Subject(typ);
            res.V2WalletSubject = v2WalletSubject;
            return res;
        }

        public class V2SubjectConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(V2Subject);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new V2Subject(V2SubjectType.V2LedgerAccountSubject)
                    {
                        V2LedgerAccountSubject = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<V2LedgerAccountSubject>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(V2LedgerAccountSubject), new V2Subject(V2SubjectType.V2LedgerAccountSubject), "V2LedgerAccountSubject"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new V2Subject(V2SubjectType.V2WalletSubject)
                    {
                        V2WalletSubject = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<V2WalletSubject>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(V2WalletSubject), new V2Subject(V2SubjectType.V2WalletSubject), "V2WalletSubject"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                V2Subject res = (V2Subject)value;

                if (res.V2LedgerAccountSubject != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.V2LedgerAccountSubject));
                    return;
                }

                if (res.V2WalletSubject != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.V2WalletSubject));
                    return;
                }
            }

        }

    }
}