//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Payments
{
    using FormanceSDK.Models.Payments;
    using FormanceSDK.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// OK.
    /// </summary>
    public class AccountResponse
    {
        /// <summary>
        /// An account held at a payment provider, surfaced through a connector.
        /// </summary>
        [JsonProperty("data")]
        public Models.Payments.Account Data { get; set; } = default!;
    }
}