//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Payments
{
    using FormanceSDK.Utils;
    using Newtonsoft.Json;

    public class ForwardBankAccountRequest
    {
        /// <summary>
        /// Identifier of the connector to forward the bank account to.
        /// </summary>
        [JsonProperty("connectorID")]
        public string ConnectorID { get; set; } = default!;
    }
}