//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Payments
{
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using System;

    public enum LegacyPaymentStatus
    {
        [JsonProperty("PENDING")]
        Pending,
        [JsonProperty("SUCCEEDED")]
        Succeeded,
        [JsonProperty("CANCELLED")]
        Cancelled,
        [JsonProperty("FAILED")]
        Failed,
        [JsonProperty("EXPIRED")]
        Expired,
        [JsonProperty("REFUNDED")]
        Refunded,
        [JsonProperty("REFUNDED_FAILURE")]
        RefundedFailure,
        [JsonProperty("DISPUTE")]
        Dispute,
        [JsonProperty("DISPUTE_WON")]
        DisputeWon,
        [JsonProperty("DISPUTE_LOST")]
        DisputeLost,
        [JsonProperty("OTHER")]
        Other,
        [JsonProperty("WAITING_FOR_VALIDATION")]
        WaitingForValidation,
        [JsonProperty("PROCESSING")]
        Processing,
        [JsonProperty("PROCESSED")]
        Processed,
        [JsonProperty("REJECTED")]
        Rejected,
        [JsonProperty("VALIDATED")]
        Validated,
        [JsonProperty("ASK_RETRIED")]
        AskRetried,
        [JsonProperty("ASK_REVERSED")]
        AskReversed,
        [JsonProperty("REVERSE_PROCESSING")]
        ReverseProcessing,
        [JsonProperty("REVERSE_FAILED")]
        ReverseFailed,
        [JsonProperty("PARTIALLY_REVERSED")]
        PartiallyReversed,
        [JsonProperty("REVERSED")]
        Reversed,
    }

    public static class LegacyPaymentStatusExtension
    {
        public static string Value(this LegacyPaymentStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static LegacyPaymentStatus ToEnum(this string value)
        {
            foreach(var field in typeof(LegacyPaymentStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is LegacyPaymentStatus)
                    {
                        return (LegacyPaymentStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum LegacyPaymentStatus");
        }
    }
}