//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Payments
{
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Plugin capability advertised by a connector. Distinct from the Formance gateway "module capabilities" (which are version-gated); these reflect what the underlying PSP integration actually exposes.
    /// </summary>
    public enum V3Capability
    {
        [JsonProperty("FETCH_ACCOUNTS")]
        FetchAccounts,
        [JsonProperty("FETCH_BALANCES")]
        FetchBalances,
        [JsonProperty("FETCH_EXTERNAL_ACCOUNTS")]
        FetchExternalAccounts,
        [JsonProperty("FETCH_PAYMENTS")]
        FetchPayments,
        [JsonProperty("FETCH_OTHERS")]
        FetchOthers,
        [JsonProperty("FETCH_ORDERS")]
        FetchOrders,
        [JsonProperty("FETCH_CONVERSIONS")]
        FetchConversions,
        [JsonProperty("CREATE_WEBHOOKS")]
        CreateWebhooks,
        [JsonProperty("TRANSLATE_WEBHOOKS")]
        TranslateWebhooks,
        [JsonProperty("CREATE_BANK_ACCOUNT")]
        CreateBankAccount,
        [JsonProperty("CREATE_TRANSFER")]
        CreateTransfer,
        [JsonProperty("CREATE_PAYOUT")]
        CreatePayout,
        [JsonProperty("ALLOW_FORMANCE_ACCOUNT_CREATION")]
        AllowFormanceAccountCreation,
        [JsonProperty("ALLOW_FORMANCE_PAYMENT_CREATION")]
        AllowFormancePaymentCreation,
    }

    public static class V3CapabilityExtension
    {
        public static string Value(this V3Capability value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static V3Capability ToEnum(this string value)
        {
            foreach(var field in typeof(V3Capability).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is V3Capability)
                    {
                        return (V3Capability)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum V3Capability");
        }
    }
}