//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Payments
{
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using System;

    public enum V3ConnectionStatusEnum
    {
        [JsonProperty("ACTIVE")]
        Active,
        [JsonProperty("ERROR")]
        Error,
    }

    public static class V3ConnectionStatusEnumExtension
    {
        public static string Value(this V3ConnectionStatusEnum value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static V3ConnectionStatusEnum ToEnum(this string value)
        {
            foreach(var field in typeof(V3ConnectionStatusEnum).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is V3ConnectionStatusEnum)
                    {
                        return (V3ConnectionStatusEnum)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum V3ConnectionStatusEnum");
        }
    }
}