//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Payments
{
    using FormanceSDK.Models.Payments;
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class V3ConnectorCapabilitiesResponse
    {
        /// <summary>
        /// Map of provider name to the capabilities its plugin advertises.
        /// </summary>
        [JsonProperty("data")]
        public Dictionary<string, List<V3Capability>> Data { get; set; } = default!;
    }
}