//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Payments
{
    using FormanceSDK.Models.Payments;
    using FormanceSDK.Utils;
    using Newtonsoft.Json;

    public class V3GetPoolResponse
    {
        /// <summary>
        /// A named group of accounts whose balances are aggregated together.
        /// </summary>
        [JsonProperty("data")]
        public V3Pool Data { get; set; } = default!;
    }
}