//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Payments
{
    using FormanceSDK.Models.Payments;
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Numerics;

    /// <summary>
    /// Immutable snapshot of an order's state at a single observation.<br/>
    /// Formance records one adjustment per distinct state the PSP reports<br/>
    /// (status change, fill progress, fee update). Events are emitted<br/>
    /// per-adjustment, not per-order — so a single order can produce many<br/>
    /// events over its lifetime.
    /// </summary>
    public class V3OrderAdjustment
    {
        /// <summary>
        /// Adjustment ID, composed from the order ID plus the state fields that define uniqueness (status, filled quantity, fee). Idempotent — replaying the same observation produces the same ID.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// PSP reference the adjustment belongs to (equal to the parent order's `reference`).
        /// </summary>
        [JsonProperty("reference")]
        public string Reference { get; set; } = default!;

        /// <summary>
        /// When Formance observed this state. Not the PSP's own timestamp — reflects ingestion time.
        /// </summary>
        [JsonProperty("createdAt")]
        public DateTime CreatedAt { get; set; } = default!;

        /// <summary>
        /// Lifecycle of an order on the exchange.<br/>
        /// `PENDING` — accepted by the exchange, not yet working.<br/>
        /// `OPEN` — live on the book, no fills yet.<br/>
        /// `PARTIALLY_FILLED` — live on the book, some base quantity filled.<br/>
        /// `FILLED` — fully filled, terminal.<br/>
        /// `CANCELLED` — cancelled by the user or system, terminal.<br/>
        /// `FAILED` — rejected by the exchange, terminal. See `error` for details.<br/>
        /// `EXPIRED` — `timeInForce` elapsed before full fill, terminal.
        /// </summary>
        [JsonProperty("status")]
        public V3OrderStatusEnum V3OrderStatusEnum { get; set; } = default!;

        /// <summary>
        /// Base asset filled at this observation, at the base asset's precision.
        /// </summary>
        [JsonProperty("baseQuantityFilled")]
        public BigInteger? BaseQuantityFilled { get; set; } = null;

        /// <summary>
        /// Cumulative fee at this observation, at `feeAsset` precision.
        /// </summary>
        [JsonProperty("fee")]
        public BigInteger? Fee { get; set; } = null;

        /// <summary>
        /// Currency the fee is denominated in, in `SYMBOL/precision` form.
        /// </summary>
        [JsonProperty("feeAsset")]
        public string? FeeAsset { get; set; } = null;

        [JsonProperty("metadata")]
        public Dictionary<string, string>? V3Metadata { get; set; } = null;

        /// <summary>
        /// Untransformed PSP response payload that produced this adjustment. Retained for debugging and replay.
        /// </summary>
        [JsonProperty("raw")]
        public V3OrderAdjustmentRaw? Raw { get; set; }
    }
}