//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Payments
{
    using FormanceSDK.Utils;
    using Newtonsoft.Json;

    public class V3PaymentServiceUserUpdateLinkRequest
    {
        /// <summary>
        /// The name of the application to be displayed to the user when they click the link (depending on the open banking provider). Note that this field might be mandatory for some open banking providers.
        /// </summary>
        [JsonProperty("applicationName")]
        public string? ApplicationName { get; set; }

        [JsonProperty("clientRedirectURL")]
        public string ClientRedirectURL { get; set; } = default!;
    }
}