//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Payments
{
    using FormanceSDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System.Numerics;

    public class V3PoolBalance
    {
        /// <summary>
        /// Asset the balance is denominated in.
        /// </summary>
        [JsonProperty("asset")]
        public string Asset { get; set; } = default!;

        /// <summary>
        /// Total held across the pool for this asset, in the asset's smallest unit.
        /// </summary>
        [JsonProperty("amount")]
        public BigInteger Amount { get; set; } = default!;

        /// <summary>
        /// Accounts contributing to this balance.
        /// </summary>
        [JsonProperty("relatedAccounts")]
        public List<string>? RelatedAccounts { get; set; } = null;
    }
}