//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace FormanceSDK.Models.Payments
{
    using FormanceSDK.Utils;
    using Newtonsoft.Json;

    public class WiseConfig
    {
        /// <summary>
        /// Human-readable name identifying this connector instance.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Identifies the payment provider this configuration targets.
        /// </summary>
        [JsonProperty("provider")]
        public string? Provider { get; set; } = "Wise";

        /// <summary>
        /// API key issued by Wise, used to authenticate the connector's requests.
        /// </summary>
        [JsonProperty("apiKey")]
        public string ApiKey { get; set; } = default!;

        /// <summary>
        /// The frequency at which the connector will try to fetch new BalanceTransaction objects from Wise API.
        /// </summary>
        [JsonProperty("pollingPeriod")]
        public string? PollingPeriod { get; set; } = "30m";
    }
}